version: 2
jobs:
  build-javascript:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: yarn
      - run: yarn build
workflows:
  version: 2
  build:
    jobs:
      - build-javascript
